= Dockerfile for lra-coordinator

The Dockerfile builds a container image of lra coordinator
which can be contacted to manage Long Running Actions, see
https://github.com/jbosstm/microprofile-sandbox/blob/master/proposals/0009-LRA/README.md

You can redefine following variables when building the image.

== Building the Dockerfile

`NARAYANA_VERSION`::
  is used only during image build and defines what version of Narayana
  will be downloaded and lra coordinator extracted from that
`LOG_LEVEL`::
  could be defined at startup, value changes log level produced by Quarkus,
  the values are standard log levels (INFO, DEBUG, TRACE...)

The lra coordinator exposes port `8080` for communication.

== Usage

```bash
# export NARAYANA_VERSION=...
podman build -t lra-coordinator --build-arg NARAYANA_VERSION=$NARAYANA_VERSION .
```

== Running localy

I you want to run locally you use the following command. This starts the container
image `lra-cordinator` you've just built and define the logging to be set to
TRACE level.

```bash
podman run -p 8080:8080 --rm -it -e LOG_LEVEL=TRACE lra-coordinator
```

== Container image at Dockerhub

The `lra-coordinator` image is available at https://hub.docker.com/r/jbosstm/lra-coordinator.
You can pull it (the tag `latest`) by running

```bash
podman pull docker.io/jbosstm/lra-coordinator
```

== Release the lra container image to Dockerhub

If you build the image you can push the new version to dockerhub with sequence

```bash
# tagging the lra-coordinator to be possible to be pushed to docker hub
podman tag lra-coordinator:latest docker.io/jbosstm/lra-coordinator:${NARAYANA_VERSION}
podman tag lra-coordinator:latest docker.io/jbosstm/lra-coordinator:latest
# logging to the docker hub
podman login docker.io
# pushing the tagged image to dockerhub
podman push docker.io/jbosstm/lra-coordinator:${NARAYANA_VERSION}
## will rewrite the image marked as 'latest' at the docker hub
podman push  docker.io/jbosstm/lra-coordinator:latest
```

== Running the lra-coordinator at OpenShift

This container image is used to start the `lra-coordinator` at OpenShift when you
use the link:../openshift-template[template] in this repo. When you import it
and create new app the container image will be downloaded from the dockerhub
and run at the OpenShift instance.
